name: Validate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "temp"]

permissions:
  contents: read
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: |
          corepack enable
          yarn set version 4.5.1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Yarn format check
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: |
          corepack enable
          yarn set version 4.5.1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Yarn lint
        run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: |
          corepack enable
          yarn set version 4.5.1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Yarn typecheck
        run: yarn typecheck
